// <auto-generated />
using System;
using CINE.GroceryTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CINE.GroceryTracker.Infrastructure.Migrations
{
    [DbContext(typeof(GroceryTrackerDbContext))]
    partial class GroceryTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("SyncStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("SyncStamp");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.ExpenseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<long>("SyncStamp")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("SyncStamp");

                    b.HasIndex("TripId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("SyncStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SyncStamp");

                    b.ToTable("Households", (string)null);
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ShareWeight")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasDefaultValue(1m);

                    b.Property<long>("SyncStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("SyncStamp");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("FromMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("SyncStamp")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ToMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FromMemberId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("SyncStamp");

                    b.HasIndex("ToMemberId");

                    b.ToTable("Settlements", (string)null);
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.ShoppingTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("PaidByMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PurchasedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<long>("SyncStamp")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("PaidByMemberId");

                    b.HasIndex("PurchasedOn");

                    b.HasIndex("StoreId");

                    b.HasIndex("SyncStamp");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("SyncStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("SyncStamp");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("CINE.GroceryTracker.Infrastructure.Data.AppliedSyncOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("OperationId");

                    b.HasIndex("AppliedAtUtc");

                    b.ToTable("AppliedSyncOperations", (string)null);
                });

            modelBuilder.Entity("CINE.GroceryTracker.Infrastructure.Data.SyncCounter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("LastStamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SyncCounters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastStamp = 0L
                        });
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Category", b =>
                {
                    b.HasOne("CINE.GroceryTracker.Domain.Model.Household", "Household")
                        .WithMany("Categories")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.ExpenseItem", b =>
                {
                    b.HasOne("CINE.GroceryTracker.Domain.Model.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CINE.GroceryTracker.Domain.Model.ShoppingTrip", "Trip")
                        .WithMany("Items")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Member", b =>
                {
                    b.HasOne("CINE.GroceryTracker.Domain.Model.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Settlement", b =>
                {
                    b.HasOne("CINE.GroceryTracker.Domain.Model.Member", "FromMember")
                        .WithMany()
                        .HasForeignKey("FromMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CINE.GroceryTracker.Domain.Model.Household", "Household")
                        .WithMany("Settlements")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CINE.GroceryTracker.Domain.Model.Member", "ToMember")
                        .WithMany()
                        .HasForeignKey("ToMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromMember");

                    b.Navigation("Household");

                    b.Navigation("ToMember");
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.ShoppingTrip", b =>
                {
                    b.HasOne("CINE.GroceryTracker.Domain.Model.Household", "Household")
                        .WithMany("Trips")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CINE.GroceryTracker.Domain.Model.Member", "PaidByMember")
                        .WithMany("Trips")
                        .HasForeignKey("PaidByMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CINE.GroceryTracker.Domain.Model.Store", "Store")
                        .WithMany("Trips")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("PaidByMember");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Store", b =>
                {
                    b.HasOne("CINE.GroceryTracker.Domain.Model.Household", "Household")
                        .WithMany("Stores")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Household", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Members");

                    b.Navigation("Settlements");

                    b.Navigation("Stores");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Member", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.ShoppingTrip", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CINE.GroceryTracker.Domain.Model.Store", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
