#!/usr/bin/env python3
"""Render text as a square SVG logo made of glyph outlines.

The repo's logos (Assets/C-logo.svg, the GroceryTracker GT logo, the LaunchHeim icon) share one
look: Kode Mono Bold in the orange #DE5833 on a transparent background. The glyphs are converted
to paths, not left as <text>. Otherwise every viewer without Kode Mono installed (browsers, icon
themes, Windows Explorer) would silently substitute another font.

Needs fontTools (`pip install fonttools`). Kode Mono is a variable font, so the bold weight is
instanced out of it here rather than needing a separate static file.

  Scripts/text_logo.py GT Applications/GroceryTracker/assets/GT-logo-optimized.svg

The SVG is always the source. Raster files (PNG, .ico) are rendered from it, never drawn directly,
and each size is rendered from the vector rather than scaled down from a big PNG, so small icons
stay sharp:
  for n in 16 24 32 48 64 128 256; do rsvg-convert -w $n -h $n logo.svg -o logo-$n.png; done
  magick logo-{16,24,32,48,64,128,256}.png logo.ico
"""
import argparse
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ORANGE = "#DE5833"
DEFAULT_FONT = Path(__file__).resolve().parent.parent / "Applications/GroceryTracker/src/UI/GroceryTracker.UI.Blazor/wwwroot/fonts/KodeMono.woff2"


def main() -> None:
  parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
  parser.add_argument("text")
  parser.add_argument("output", type=Path)
  parser.add_argument("--font", type=Path, default=DEFAULT_FONT, help="Kode Mono (variable) .ttf/.woff2")
  parser.add_argument("--weight", type=float, default=700)
  parser.add_argument("--color", default=ORANGE)
  parser.add_argument("--size", type=int, default=512, help="width and height of the square canvas")
  parser.add_argument("--padding", type=float, default=0.125, help="margin per side, as a fraction of the size")
  args = parser.parse_args()

  font = TTFont(args.font)
  if "fvar" in font:
    font = instantiateVariableFont(font, {"wght": args.weight})
  glyphs = font.getGlyphSet()
  cmap = font.getBestCmap()

  # Lay the glyphs out on their advance widths, all into one path, so the letters keep the font's
  # own spacing and the whole word can be centred by its ink bounds rather than its advance box.
  path_pen = SVGPathPen(glyphs)
  bounds_pen = BoundsPen(glyphs)
  x = 0
  for char in args.text:
    glyph = glyphs[cmap[ord(char)]]
    glyph.draw(TransformPen(path_pen, (1, 0, 0, 1, x, 0)))
    glyph.draw(TransformPen(bounds_pen, (1, 0, 0, 1, x, 0)))
    x += glyph.width

  x0, y0, x1, y1 = bounds_pen.bounds
  width, height = x1 - x0, y1 - y0
  scale = args.size * (1 - 2 * args.padding) / max(width, height)
  # Font units point y up and SVG points y down, hence the negative y scale.
  tx = (args.size - width * scale) / 2 - x0 * scale
  ty = (args.size + height * scale) / 2 + y0 * scale

  args.output.write_text(
    f'<svg xmlns="http://www.w3.org/2000/svg" width="{args.size}" height="{args.size}" viewBox="0 0 {args.size} {args.size}">'
    f"<title>{args.text}</title>"
    f"<!-- \"{args.text}\" in Kode Mono (SIL OFL 1.1) as outlines, generated by Scripts/text_logo.py. -->"
    f'<path fill="{args.color}" transform="translate({tx:.2f} {ty:.2f}) scale({scale:.5f} {-scale:.5f})" d="{path_pen.getCommands()}"/>'
    "</svg>\n"
  )


if __name__ == "__main__":
  main()
